# Generated by Django 5.1.5 on 2025-01-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecentVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('doctor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('treatment', models.TextField()),
                ('diseases', models.JSONField()),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('last_visit', models.DateField()),
                ('dob', models.DateField()),
                ('blood_type', models.CharField(max_length=3)),
                ('next_appointment', models.DateField(blank=True, null=True)),
                ('medications', models.JSONField()),
                ('allergies', models.JSONField()),
                ('prescriptions', models.ManyToManyField(related_name='patients', to='api.prescription')),
                ('recent_visits', models.ManyToManyField(related_name='patients', to='api.recentvisit')),
            ],
        ),
    ]
