# Generated by Django 5.1.5 on 2025-02-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='place',
            field=models.CharField(blank=True, choices=[('Virtual', 'Virtual'), ('In-person', 'In-person')], default='in-person', max_length=255),
        ),
    ]
