# Generated by Django 5.1.5 on 2025-02-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, default='Patient', max_length=50),
        ),
    ]
