# Generated by Django 5.1.5 on 2025-03-15 15:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('date', models.DateField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('direction', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, choices=[('immobilier', 'immobilier'), ('publicite', 'publicite'), ('fourniture consommable', 'fourniture consommable'), ('capital humain', 'capital humain'), ("rembouresement d'empreint", "rembouresement d'empreint")], default='immobilier', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('date', models.DateField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, choices=[('consultation', 'consultation'), ('prescription', 'prescription'), ('analyse', 'analyse'), ('pret bancaire', 'pret bancaire')], default='consultation', max_length=255)),
            ],
        ),
    ]
