# Generated by Django 5.1.5 on 2025-03-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Specialty',
            field=models.CharField(blank=True, default='Generalist', max_length=50),
        ),
    ]
