# Generated by Django 5.1.5 on 2025-01-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_patient_recent_visits_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='patients',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='patients',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='patients', to='api.allergy'),
        ),
        migrations.AddField(
            model_name='patient',
            name='appointment',
            field=models.ManyToManyField(blank=True, related_name='patients', to='api.appointment'),
        ),
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.ManyToManyField(blank=True, related_name='patients', to='api.disease'),
        ),
        migrations.AddField(
            model_name='patient',
            name='visit',
            field=models.ManyToManyField(blank=True, related_name='patients', to='api.visit'),
        ),
    ]
