# Generated by Django 5.1.5 on 2025-01-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_allergy_patients_remove_appointment_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='doctor',
        ),
    ]
