# Generated by Django 5.1.5 on 2025-01-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_visit_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
