# Generated by Django 5.1.5 on 2025-02-02 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patient_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 1, 3)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.CharField(blank=True, help_text='Name of the medication', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
