# Generated by Django 5.1.5 on 2025-02-05 15:28

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patient_options_visit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='assurance_number',
            field=models.CharField(blank=True, default='123456789', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, default='Morocco', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='doctor',
            name='inassurance',
            field=models.CharField(blank=True, default='123456789', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, default='123456789', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(blank=True, default='Doctor', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(blank=True, default='Doctor', max_length=50),
        ),
    ]
