# Generated by Django 5.1.5 on 2025-01-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='patient', to='api.allergy'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='appointment',
            field=models.ManyToManyField(blank=True, related_name='patient', to='api.appointment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.ManyToManyField(blank=True, related_name='patient', to='api.disease'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='visit',
            field=models.ManyToManyField(blank=True, related_name='patient', to='api.visit'),
        ),
    ]
