# Generated by Django 5.1.5 on 2025-02-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_doctor_email_alter_doctor_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['username']},
        ),
    ]
