# Generated by Django 5.1.5 on 2025-02-05 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_doctor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('date', models.DateField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('source', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
