# Generated by Django 5.1.5 on 2025-02-05 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_message_conversation_conversation_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='assurance_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='inassurance',
        ),
    ]
