# Generated by Django 5.1.5 on 2025-02-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_doctor_assurance_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sexe',
            field=models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], default='male', max_length=8),
        ),
    ]
