# Generated by Django 5.1.5 on 2025-02-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_appointment_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='sexe',
        ),
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], default='male', max_length=8),
        ),
    ]
