# Generated by Django 5.1.5 on 2025-02-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patient_first_name'),
        ('api', '0013_remove_appointment_sexe_patient_sexe'),
    ]

    operations = [
    ]
